version: "2"

services:

  php:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    tty: true
    stdin_open: true
    environment:
      - PROVISIONING_API_URL
      - SYRUP_QUEUE_URL
      - PROVISIONING_API_TOKEN
      - PROVISIONING_API_TOKEN_SECOND_PROJECT
