version: "2"

services:

  tests:
    build: .
    image: keboola/provisioning-client
    volumes:
      - .:/code
    working_dir: /code
    tty: true
    stdin_open: true
    environment:
      - STORAGE_API_URL
      - PROVISIONING_API_URL
      - SYRUP_QUEUE_URL
      - PROVISIONING_API_TOKEN
